from typing import List

class TrieNode:
    def __init__(self):
        self.children={}
        self.wordFlag=False

class Trie:
    def __init__(self):
        self.root=TrieNode()

    def insert(self, word):
        node=self.root
        for c in word:
            if not c in node.children:
                node.children[c]=TrieNode()
            node=node.children[c]
        node.wordFlag=True                  # Set word flag to true for last char to differentiate search by whole word or prefix

    def startsWith(self, prefix):
        node=self.root
        for c in prefix:
            if not c in node.children:
                return (False, False)
            node=node.children[c]
        isPrefix=node is not None
        isWord=isPrefix and node.wordFlag
        return (isPrefix, isWord)

class Solution:

    # Use Trie for words lookup
    # Collection when word found in Trie and mark it used, since each word is only found once
    # Use max length of word in words to limit recursion depth
    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:

        dirs=[(-1,0),(1,0),(0,-1),(0,1)]

        def valid(x,y):
            return x>=0 and x<m and y>=0 and y<n

        def dfs(x, y, path):
            isPrefix, isWord = trie.startsWith(path)
            if isPrefix and isWord:
                word=''.join(path)
                if not word in usedWords:
                    result.append(word)
                    usedWords[word]=1
                    
            if not isPrefix or len(path)>=maxWordLen:
                return
            visited[x][y]=True
            for dx,dy in dirs:
                nx,ny=x+dx,y+dy
                if valid(nx,ny) and not visited[nx][ny]:
                    path.append(board[nx][ny])
                    dfs(nx,ny,path)
                    path.pop()
            visited[x][y]=False

        if not board or not words: return []
        m,n=len(board),len(board[0])
        trie=Trie()
        for word in words:
            trie.insert(word)
        visited=[[False]*n for _ in range(m)]
        result=[]
        usedWords={}                            # Each word is only used once
        maxWordLen=max([len(word) for word in words])
        for i in range(m):
            for j in range(n):
                dfs(x=i,y=j,path=[board[i][j]])
        return result


import unittest

class TestSolution(unittest.TestCase):
    def testFindWords(self):
        s = Solution()
        # self.assertEqual(s.findWords(board = [["m","b","c","d","e","f","g","h","i","j","k","l"],
        #                                       ["n","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["o","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["p","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["q","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["r","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["s","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["t","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["u","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["v","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["w","a","a","a","a","a","a","a","a","a","a","a"],
        #                                       ["x","y","z","a","a","a","a","a","a","a","a","a"]], 
        #                              words = ["aaaaaaaaaa",
        #                                         "aaaaaaaaab",
        #                                         "aaaaaaaaac",
        #                                         "aaaaaaaaad",
        #                                         "aaaaaaaaae",
        #                                         "aaaaaaaaaf",
        #                                         "aaaaaaaaag",
        #                                         "aaaaaaaaah",
        #                                         "aaaaaaaaai",
        #                                         "aaaaaaaaaj",
        #                                         "aaaaaaaaak",
        #                                         "aaaaaaaaal",
        #                                         "aaaaaaaaam",
        #                                         "aaaaaaaaan",
        #                                         "aaaaaaaaao",
        #                                         "aaaaaaaaap",
        #                                         "aaaaaaaaaq",
        #                                         "aaaaaaaaar",
        #                                         "aaaaaaaaas",
        #                                         "aaaaaaaaat",
        #                                         "aaaaaaaaau",
        #                                         "aaaaaaaaav",
        #                                         "aaaaaaaaaw",
        #                                         "aaaaaaaaax",
        #                                         "aaaaaaaaay",
        #                                         "aaaaaaaaaz",
        #                                         "aaaaaaaaba",
        #                                         "aaaaaaaabb",
        #                                         "aaaaaaaabc",
        #                                         "aaaaaaaabd",
        #                                         "aaaaaaaabe",
        #                                         "aaaaaaaabf",
        #                                         "aaaaaaaabg",
        #                                         "aaaaaaaabh",
        #                                         "aaaaaaaabi",
        #                                         "aaaaaaaabj",
        #                                         "aaaaaaaabk",
        #                                         "aaaaaaaabl",
        #                                         "aaaaaaaabm",
        #                                         "aaaaaaaabn",
        #                                         "aaaaaaaabo",
        #                                         "aaaaaaaabp",
        #                                         "aaaaaaaabq",
        #                                         "aaaaaaaabr",
        #                                         "aaaaaaaabs",
        #                                         "aaaaaaaabt",
        #                                         "aaaaaaaabu",
        #                                         "aaaaaaaabv",
        #                                         "aaaaaaaabw",
        #                                         "aaaaaaaabx",
        #                                         "aaaaaaaaby",
        #                                         "aaaaaaaabz",
        #                                         "aaaaaaaaca",
        #                                         "aaaaaaaacb",
        #                                         "aaaaaaaacc",
        #                                         "aaaaaaaacd",
        #                                         "aaaaaaaace",
        #                                         "aaaaaaaacf",
        #                                         "aaaaaaaacg",
        #                                         "aaaaaaaach",
        #                                         "aaaaaaaaci",
        #                                         "aaaaaaaacj",
        #                                         "aaaaaaaack",
        #                                         "aaaaaaaacl",
        #                                         "aaaaaaaacm",
        #                                         "aaaaaaaacn",
        #                                         "aaaaaaaaco",
        #                                         "aaaaaaaacp",
        #                                         "aaaaaaaacq",
        #                                         "aaaaaaaacr",
        #                                         "aaaaaaaacs",
        #                                         "aaaaaaaact",
        #                                         "aaaaaaaacu",
        #                                         "aaaaaaaacv",
        #                                         "aaaaaaaacw",
        #                                         "aaaaaaaacx",
        #                                         "aaaaaaaacy",
        #                                         "aaaaaaaacz",
        #                                         "aaaaaaaada",
        #                                         "aaaaaaaadb",
        #                                         "aaaaaaaadc",
        #                                         "aaaaaaaadd",
        #                                         "aaaaaaaade",
        #                                         "aaaaaaaadf",
        #                                         "aaaaaaaadg",
        #                                         "aaaaaaaadh",
        #                                         "aaaaaaaadi",
        #                                         "aaaaaaaadj",
        #                                         "aaaaaaaadk",
        #                                         "aaaaaaaadl",
        #                                         "aaaaaaaadm",
        #                                         "aaaaaaaadn",
        #                                         "aaaaaaaado",
        #                                         "aaaaaaaadp",
        #                                         "aaaaaaaadq",
        #                                         "aaaaaaaadr",
        #                                         "aaaaaaaads",
        #                                         "aaaaaaaadt",
        #                                         "aaaaaaaadu",
        #                                         "aaaaaaaadv",
        #                                         "aaaaaaaadw",
        #                                         "aaaaaaaadx",
        #                                         "aaaaaaaady",
        #                                         "aaaaaaaadz",
        #                                         "aaaaaaaaea",
        #                                         "aaaaaaaaeb",
        #                                         "aaaaaaaaec",
        #                                         "aaaaaaaaed",
        #                                         "aaaaaaaaee",
        #                                         "aaaaaaaaef",
        #                                         "aaaaaaaaeg",
        #                                         "aaaaaaaaeh",
        #                                         "aaaaaaaaei",
        #                                         "aaaaaaaaej",
        #                                         "aaaaaaaaek",
        #                                         "aaaaaaaael",
        #                                         "aaaaaaaaem",
        #                                         "aaaaaaaaen",
        #                                         "aaaaaaaaeo",
        #                                         "aaaaaaaaep",
        #                                         "aaaaaaaaeq",
        #                                         "aaaaaaaaer",
        #                                         "aaaaaaaaes",
        #                                         "aaaaaaaaet",
        #                                         "aaaaaaaaeu",
        #                                         "aaaaaaaaev",
        #                                         "aaaaaaaaew",
        #                                         "aaaaaaaaex",
        #                                         "aaaaaaaaey",
        #                                         "aaaaaaaaez",
        #                                         "aaaaaaaafa",
        #                                         "aaaaaaaafb",
        #                                         "aaaaaaaafc",
        #                                         "aaaaaaaafd",
        #                                         "aaaaaaaafe",
        #                                         "aaaaaaaaff",
        #                                         "aaaaaaaafg",
        #                                         "aaaaaaaafh",
        #                                         "aaaaaaaafi",
        #                                         "aaaaaaaafj",
        #                                         "aaaaaaaafk",
        #                                         "aaaaaaaafl",
        #                                         "aaaaaaaafm",
        #                                         "aaaaaaaafn",
        #                                         "aaaaaaaafo",
        #                                         "aaaaaaaafp",
        #                                         "aaaaaaaafq",
        #                                         "aaaaaaaafr",
        #                                         "aaaaaaaafs",
        #                                         "aaaaaaaaft",
        #                                         "aaaaaaaafu",
        #                                         "aaaaaaaafv",
        #                                         "aaaaaaaafw",
        #                                         "aaaaaaaafx",
        #                                         "aaaaaaaafy",
        #                                         "aaaaaaaafz",
        #                                         "aaaaaaaaga",
        #                                         "aaaaaaaagb",
        #                                         "aaaaaaaagc",
        #                                         "aaaaaaaagd",
        #                                         "aaaaaaaage",
        #                                         "aaaaaaaagf",
        #                                         "aaaaaaaagg",
        #                                         "aaaaaaaagh",
        #                                         "aaaaaaaagi",
        #                                         "aaaaaaaagj",
        #                                         "aaaaaaaagk",
        #                                         "aaaaaaaagl",
        #                                         "aaaaaaaagm",
        #                                         "aaaaaaaagn",
        #                                         "aaaaaaaago",
        #                                         "aaaaaaaagp",
        #                                         "aaaaaaaagq",
        #                                         "aaaaaaaagr",
        #                                         "aaaaaaaags",
        #                                         "aaaaaaaagt",
        #                                         "aaaaaaaagu",
        #                                         "aaaaaaaagv",
        #                                         "aaaaaaaagw",
        #                                         "aaaaaaaagx",
        #                                         "aaaaaaaagy",
        #                                         "aaaaaaaagz",
        #                                         "aaaaaaaaha",
        #                                         "aaaaaaaahb",
        #                                         "aaaaaaaahc",
        #                                         "aaaaaaaahd",
        #                                         "aaaaaaaahe",
        #                                         "aaaaaaaahf",
        #                                         "aaaaaaaahg",
        #                                         "aaaaaaaahh",
        #                                         "aaaaaaaahi",
        #                                         "aaaaaaaahj",
        #                                         "aaaaaaaahk",
        #                                         "aaaaaaaahl",
        #                                         "aaaaaaaahm",
        #                                         "aaaaaaaahn",
        #                                         "aaaaaaaaho",
        #                                         "aaaaaaaahp",
        #                                         "aaaaaaaahq",
        #                                         "aaaaaaaahr",
        #                                         "aaaaaaaahs",
        #                                         "aaaaaaaaht",
        #                                         "aaaaaaaahu",
        #                                         "aaaaaaaahv",
        #                                         "aaaaaaaahw",
        #                                         "aaaaaaaahx",
        #                                         "aaaaaaaahy",
        #                                         "aaaaaaaahz",
        #                                         "aaaaaaaaia",
        #                                         "aaaaaaaaib",
        #                                         "aaaaaaaaic",
        #                                         "aaaaaaaaid",
        #                                         "aaaaaaaaie",
        #                                         "aaaaaaaaif",
        #                                         "aaaaaaaaig",
        #                                         "aaaaaaaaih",
        #                                         "aaaaaaaaii",
        #                                         "aaaaaaaaij",
        #                                         "aaaaaaaaik",
        #                                         "aaaaaaaail",
        #                                         "aaaaaaaaim",
        #                                         "aaaaaaaain",
        #                                         "aaaaaaaaio",
        #                                         "aaaaaaaaip",
        #                                         "aaaaaaaaiq",
        #                                         "aaaaaaaair",
        #                                         "aaaaaaaais",
        #                                         "aaaaaaaait",
        #                                         "aaaaaaaaiu",
        #                                         "aaaaaaaaiv",
        #                                         "aaaaaaaaiw",
        #                                         "aaaaaaaaix",
        #                                         "aaaaaaaaiy",
        #                                         "aaaaaaaaiz",
        #                                         "aaaaaaaaja",
        #                                         "aaaaaaaajb",
        #                                         "aaaaaaaajc",
        #                                         "aaaaaaaajd",
        #                                         "aaaaaaaaje",
        #                                         "aaaaaaaajf",
        #                                         "aaaaaaaajg",
        #                                         "aaaaaaaajh",
        #                                         "aaaaaaaaji",
        #                                         "aaaaaaaajj",
        #                                         "aaaaaaaajk",
        #                                         "aaaaaaaajl",
        #                                         "aaaaaaaajm",
        #                                         "aaaaaaaajn",
        #                                         "aaaaaaaajo",
        #                                         "aaaaaaaajp",
        #                                         "aaaaaaaajq",
        #                                         "aaaaaaaajr",
        #                                         "aaaaaaaajs",
        #                                         "aaaaaaaajt",
        #                                         "aaaaaaaaju",
        #                                         "aaaaaaaajv",
        #                                         "aaaaaaaajw",
        #                                         "aaaaaaaajx",
        #                                         "aaaaaaaajy",
        #                                         "aaaaaaaajz",
        #                                         "aaaaaaaaka",
        #                                         "aaaaaaaakb",
        #                                         "aaaaaaaakc",
        #                                         "aaaaaaaakd",
        #                                         "aaaaaaaake",
        #                                         "aaaaaaaakf",
        #                                         "aaaaaaaakg",
        #                                         "aaaaaaaakh",
        #                                         "aaaaaaaaki",
        #                                         "aaaaaaaakj",
        #                                         "aaaaaaaakk",
        #                                         "aaaaaaaakl",
        #                                         "aaaaaaaakm",
        #                                         "aaaaaaaakn",
        #                                         "aaaaaaaako",
        #                                         "aaaaaaaakp",
        #                                         "aaaaaaaakq",
        #                                         "aaaaaaaakr",
        #                                         "aaaaaaaaks",
        #                                         "aaaaaaaakt",
        #                                         "aaaaaaaaku",
        #                                         "aaaaaaaakv",
        #                                         "aaaaaaaakw",
        #                                         "aaaaaaaakx",
        #                                         "aaaaaaaaky",
        #                                         "aaaaaaaakz",
        #                                         "aaaaaaaala",
        #                                         "aaaaaaaalb",
        #                                         "aaaaaaaalc",
        #                                         "aaaaaaaald",
        #                                         "aaaaaaaale",
        #                                         "aaaaaaaalf",
        #                                         "aaaaaaaalg",
        #                                         "aaaaaaaalh",
        #                                         "aaaaaaaali",
        #                                         "aaaaaaaalj",
        #                                         "aaaaaaaalk",
        #                                         "aaaaaaaall",
        #                                         "aaaaaaaalm",
        #                                         "aaaaaaaaln",
        #                                         "aaaaaaaalo",
        #                                         "aaaaaaaalp",
        #                                         "aaaaaaaalq",
        #                                         "aaaaaaaalr",
        #                                         "aaaaaaaals",
        #                                         "aaaaaaaalt",
        #                                         "aaaaaaaalu",
        #                                         "aaaaaaaalv",
        #                                         "aaaaaaaalw",
        #                                         "aaaaaaaalx",
        #                                         "aaaaaaaaly",
        #                                         "aaaaaaaalz",
        #                                         "aaaaaaaama",
        #                                         "aaaaaaaamb",
        #                                         "aaaaaaaamc",
        #                                         "aaaaaaaamd",
        #                                         "aaaaaaaame",
        #                                         "aaaaaaaamf",
        #                                         "aaaaaaaamg",
        #                                         "aaaaaaaamh",
        #                                         "aaaaaaaami",
        #                                         "aaaaaaaamj",
        #                                         "aaaaaaaamk",
        #                                         "aaaaaaaaml",
        #                                         "aaaaaaaamm",
        #                                         "aaaaaaaamn",
        #                                         "aaaaaaaamo",
        #                                         "aaaaaaaamp",
        #                                         "aaaaaaaamq",
        #                                         "aaaaaaaamr",
        #                                         "aaaaaaaams",
        #                                         "aaaaaaaamt",
        #                                         "aaaaaaaamu",
        #                                         "aaaaaaaamv",
        #                                         "aaaaaaaamw",
        #                                         "aaaaaaaamx",
        #                                         "aaaaaaaamy",
        #                                         "aaaaaaaamz",
        #                                         "aaaaaaaana",
        #                                         "aaaaaaaanb",
        #                                         "aaaaaaaanc",
        #                                         "aaaaaaaand",
        #                                         "aaaaaaaane",
        #                                         "aaaaaaaanf",
        #                                         "aaaaaaaang",
        #                                         "aaaaaaaanh",
        #                                         "aaaaaaaani",
        #                                         "aaaaaaaanj",
        #                                         "aaaaaaaank",
        #                                         "aaaaaaaanl",
        #                                         "aaaaaaaanm",
        #                                         "aaaaaaaann",
        #                                         "aaaaaaaano",
        #                                         "aaaaaaaanp",
        #                                         "aaaaaaaanq",
        #                                         "aaaaaaaanr",
        #                                         "aaaaaaaans",
        #                                         "aaaaaaaant",
        #                                         "aaaaaaaanu",
        #                                         "aaaaaaaanv",
        #                                         "aaaaaaaanw",
        #                                         "aaaaaaaanx",
        #                                         "aaaaaaaany",
        #                                         "aaaaaaaanz",
        #                                         "aaaaaaaaoa",
        #                                         "aaaaaaaaob",
        #                                         "aaaaaaaaoc",
        #                                         "aaaaaaaaod",
        #                                         "aaaaaaaaoe",
        #                                         "aaaaaaaaof",
        #                                         "aaaaaaaaog",
        #                                         "aaaaaaaaoh",
        #                                         "aaaaaaaaoi",
        #                                         "aaaaaaaaoj",
        #                                         "aaaaaaaaok",
        #                                         "aaaaaaaaol",
        #                                         "aaaaaaaaom",
        #                                         "aaaaaaaaon",
        #                                         "aaaaaaaaoo",
        #                                         "aaaaaaaaop",
        #                                         "aaaaaaaaoq",
        #                                         "aaaaaaaaor",
        #                                         "aaaaaaaaos",
        #                                         "aaaaaaaaot",
        #                                         "aaaaaaaaou",
        #                                         "aaaaaaaaov",
        #                                         "aaaaaaaaow",
        #                                         "aaaaaaaaox",
        #                                         "aaaaaaaaoy",
        #                                         "aaaaaaaaoz",
        #                                         "aaaaaaaapa",
        #                                         "aaaaaaaapb",
        #                                         "aaaaaaaapc",
        #                                         "aaaaaaaapd",
        #                                         "aaaaaaaape",
        #                                         "aaaaaaaapf",
        #                                         "aaaaaaaapg",
        #                                         "aaaaaaaaph",
        #                                         "aaaaaaaapi",
        #                                         "aaaaaaaapj",
        #                                         "aaaaaaaapk",
        #                                         "aaaaaaaapl",
        #                                         "aaaaaaaapm",
        #                                         "aaaaaaaapn",
        #                                         "aaaaaaaapo",
        #                                         "aaaaaaaapp",
        #                                         "aaaaaaaapq",
        #                                         "aaaaaaaapr",
        #                                         "aaaaaaaaps",
        #                                         "aaaaaaaapt",
        #                                         "aaaaaaaapu",
        #                                         "aaaaaaaapv",
        #                                         "aaaaaaaapw",
        #                                         "aaaaaaaapx",
        #                                         "aaaaaaaapy",
        #                                         "aaaaaaaapz",
        #                                         "aaaaaaaaqa",
        #                                         "aaaaaaaaqb",
        #                                         "aaaaaaaaqc",
        #                                         "aaaaaaaaqd",
        #                                         "aaaaaaaaqe",
        #                                         "aaaaaaaaqf",
        #                                         "aaaaaaaaqg",
        #                                         "aaaaaaaaqh",
        #                                         "aaaaaaaaqi",
        #                                         "aaaaaaaaqj",
        #                                         "aaaaaaaaqk",
        #                                         "aaaaaaaaql",
        #                                         "aaaaaaaaqm",
        #                                         "aaaaaaaaqn",
        #                                         "aaaaaaaaqo",
        #                                         "aaaaaaaaqp",
        #                                         "aaaaaaaaqq",
        #                                         "aaaaaaaaqr",
        #                                         "aaaaaaaaqs",
        #                                         "aaaaaaaaqt",
        #                                         "aaaaaaaaqu",
        #                                         "aaaaaaaaqv",
        #                                         "aaaaaaaaqw",
        #                                         "aaaaaaaaqx",
        #                                         "aaaaaaaaqy",
        #                                         "aaaaaaaaqz",
        #                                         "aaaaaaaara",
        #                                         "aaaaaaaarb",
        #                                         "aaaaaaaarc",
        #                                         "aaaaaaaard",
        #                                         "aaaaaaaare",
        #                                         "aaaaaaaarf",
        #                                         "aaaaaaaarg",
        #                                         "aaaaaaaarh",
        #                                         "aaaaaaaari",
        #                                         "aaaaaaaarj",
        #                                         "aaaaaaaark",
        #                                         "aaaaaaaarl",
        #                                         "aaaaaaaarm",
        #                                         "aaaaaaaarn",
        #                                         "aaaaaaaaro",
        #                                         "aaaaaaaarp",
        #                                         "aaaaaaaarq",
        #                                         "aaaaaaaarr",
        #                                         "aaaaaaaars",
        #                                         "aaaaaaaart",
        #                                         "aaaaaaaaru",
        #                                         "aaaaaaaarv",
        #                                         "aaaaaaaarw",
        #                                         "aaaaaaaarx",
        #                                         "aaaaaaaary",
        #                                         "aaaaaaaarz",
        #                                         "aaaaaaaasa",
        #                                         "aaaaaaaasb",
        #                                         "aaaaaaaasc",
        #                                         "aaaaaaaasd",
        #                                         "aaaaaaaase",
        #                                         "aaaaaaaasf",
        #                                         "aaaaaaaasg",
        #                                         "aaaaaaaash",
        #                                         "aaaaaaaasi",
        #                                         "aaaaaaaasj",
        #                                         "aaaaaaaask",
        #                                         "aaaaaaaasl",
        #                                         "aaaaaaaasm",
        #                                         "aaaaaaaasn",
        #                                         "aaaaaaaaso",
        #                                         "aaaaaaaasp",
        #                                         "aaaaaaaasq",
        #                                         "aaaaaaaasr",
        #                                         "aaaaaaaass",
        #                                         "aaaaaaaast",
        #                                         "aaaaaaaasu",
        #                                         "aaaaaaaasv",
        #                                         "aaaaaaaasw",
        #                                         "aaaaaaaasx",
        #                                         "aaaaaaaasy",
        #                                         "aaaaaaaasz",
        #                                         "aaaaaaaata",
        #                                         "aaaaaaaatb",
        #                                         "aaaaaaaatc",
        #                                         "aaaaaaaatd",
        #                                         "aaaaaaaate",
        #                                         "aaaaaaaatf",
        #                                         "aaaaaaaatg",
        #                                         "aaaaaaaath",
        #                                         "aaaaaaaati",
        #                                         "aaaaaaaatj",
        #                                         "aaaaaaaatk",
        #                                         "aaaaaaaatl",
        #                                         "aaaaaaaatm",
        #                                         "aaaaaaaatn",
        #                                         "aaaaaaaato",
        #                                         "aaaaaaaatp",
        #                                         "aaaaaaaatq",
        #                                         "aaaaaaaatr",
        #                                         "aaaaaaaats",
        #                                         "aaaaaaaatt",
        #                                         "aaaaaaaatu",
        #                                         "aaaaaaaatv",
        #                                         "aaaaaaaatw",
        #                                         "aaaaaaaatx",
        #                                         "aaaaaaaaty",
        #                                         "aaaaaaaatz",
        #                                         "aaaaaaaaua",
        #                                         "aaaaaaaaub",
        #                                         "aaaaaaaauc",
        #                                         "aaaaaaaaud",
        #                                         "aaaaaaaaue",
        #                                         "aaaaaaaauf",
        #                                         "aaaaaaaaug",
        #                                         "aaaaaaaauh",
        #                                         "aaaaaaaaui",
        #                                         "aaaaaaaauj",
        #                                         "aaaaaaaauk",
        #                                         "aaaaaaaaul",
        #                                         "aaaaaaaaum",
        #                                         "aaaaaaaaun",
        #                                         "aaaaaaaauo",
        #                                         "aaaaaaaaup",
        #                                         "aaaaaaaauq",
        #                                         "aaaaaaaaur",
        #                                         "aaaaaaaaus",
        #                                         "aaaaaaaaut",
        #                                         "aaaaaaaauu",
        #                                         "aaaaaaaauv",
        #                                         "aaaaaaaauw",
        #                                         "aaaaaaaaux",
        #                                         "aaaaaaaauy",
        #                                         "aaaaaaaauz",
        #                                         "aaaaaaaava",
        #                                         "aaaaaaaavb",
        #                                         "aaaaaaaavc",
        #                                         "aaaaaaaavd",
        #                                         "aaaaaaaave",
        #                                         "aaaaaaaavf",
        #                                         "aaaaaaaavg",
        #                                         "aaaaaaaavh",
        #                                         "aaaaaaaavi",
        #                                         "aaaaaaaavj",
        #                                         "aaaaaaaavk",
        #                                         "aaaaaaaavl",
        #                                         "aaaaaaaavm",
        #                                         "aaaaaaaavn",
        #                                         "aaaaaaaavo",
        #                                         "aaaaaaaavp",
        #                                         "aaaaaaaavq",
        #                                         "aaaaaaaavr",
        #                                         "aaaaaaaavs",
        #                                         "aaaaaaaavt",
        #                                         "aaaaaaaavu",
        #                                         "aaaaaaaavv",
        #                                         "aaaaaaaavw",
        #                                         "aaaaaaaavx",
        #                                         "aaaaaaaavy",
        #                                         "aaaaaaaavz",
        #                                         "aaaaaaaawa",
        #                                         "aaaaaaaawb",
        #                                         "aaaaaaaawc",
        #                                         "aaaaaaaawd",
        #                                         "aaaaaaaawe",
        #                                         "aaaaaaaawf",
        #                                         "aaaaaaaawg",
        #                                         "aaaaaaaawh",
        #                                         "aaaaaaaawi",
        #                                         "aaaaaaaawj",
        #                                         "aaaaaaaawk",
        #                                         "aaaaaaaawl",
        #                                         "aaaaaaaawm",
        #                                         "aaaaaaaawn",
        #                                         "aaaaaaaawo",
        #                                         "aaaaaaaawp",
        #                                         "aaaaaaaawq",
        #                                         "aaaaaaaawr",
        #                                         "aaaaaaaaws",
        #                                         "aaaaaaaawt",
        #                                         "aaaaaaaawu",
        #                                         "aaaaaaaawv",
        #                                         "aaaaaaaaww",
        #                                         "aaaaaaaawx",
        #                                         "aaaaaaaawy",
        #                                         "aaaaaaaawz",
        #                                         "aaaaaaaaxa",
        #                                         "aaaaaaaaxb",
        #                                         "aaaaaaaaxc",
        #                                         "aaaaaaaaxd",
        #                                         "aaaaaaaaxe",
        #                                         "aaaaaaaaxf",
        #                                         "aaaaaaaaxg",
        #                                         "aaaaaaaaxh",
        #                                         "aaaaaaaaxi",
        #                                         "aaaaaaaaxj",
        #                                         "aaaaaaaaxk",
        #                                         "aaaaaaaaxl",
        #                                         "aaaaaaaaxm",
        #                                         "aaaaaaaaxn",
        #                                         "aaaaaaaaxo",
        #                                         "aaaaaaaaxp",
        #                                         "aaaaaaaaxq",
        #                                         "aaaaaaaaxr",
        #                                         "aaaaaaaaxs",
        #                                         "aaaaaaaaxt",
        #                                         "aaaaaaaaxu",
        #                                         "aaaaaaaaxv",
        #                                         "aaaaaaaaxw",
        #                                         "aaaaaaaaxx",
        #                                         "aaaaaaaaxy",
        #                                         "aaaaaaaaxz",
        #                                         "aaaaaaaaya",
        #                                         "aaaaaaaayb",
        #                                         "aaaaaaaayc",
        #                                         "aaaaaaaayd",
        #                                         "aaaaaaaaye",
        #                                         "aaaaaaaayf",
        #                                         "aaaaaaaayg",
        #                                         "aaaaaaaayh",
        #                                         "aaaaaaaayi",
        #                                         "aaaaaaaayj",
        #                                         "aaaaaaaayk",
        #                                         "aaaaaaaayl",
        #                                         "aaaaaaaaym",
        #                                         "aaaaaaaayn",
        #                                         "aaaaaaaayo",
        #                                         "aaaaaaaayp",
        #                                         "aaaaaaaayq",
        #                                         "aaaaaaaayr",
        #                                         "aaaaaaaays",
        #                                         "aaaaaaaayt",
        #                                         "aaaaaaaayu",
        #                                         "aaaaaaaayv",
        #                                         "aaaaaaaayw",
        #                                         "aaaaaaaayx",
        #                                         "aaaaaaaayy",
        #                                         "aaaaaaaayz",
        #                                         "aaaaaaaaza",
        #                                         "aaaaaaaazb",
        #                                         "aaaaaaaazc",
        #                                         "aaaaaaaazd",
        #                                         "aaaaaaaaze",
        #                                         "aaaaaaaazf",
        #                                         "aaaaaaaazg",
        #                                         "aaaaaaaazh",
        #                                         "aaaaaaaazi",
        #                                         "aaaaaaaazj",
        #                                         "aaaaaaaazk",
        #                                         "aaaaaaaazl",
        #                                         "aaaaaaaazm",
        #                                         "aaaaaaaazn",
        #                                         "aaaaaaaazo",
        #                                         "aaaaaaaazp",
        #                                         "aaaaaaaazq",
        #                                         "aaaaaaaazr",
        #                                         "aaaaaaaazs",
        #                                         "aaaaaaaazt",
        #                                         "aaaaaaaazu",
        #                                         "aaaaaaaazv",
        #                                         "aaaaaaaazw",
        #                                         "aaaaaaaazx",
        #                                         "aaaaaaaazy",
        #                                         "aaaaaaaazz"]), 
        #                              [])
        self.assertEqual(s.findWords(board = [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]], 
                                     words = ["oath","pea","eat","rain","oathi","oathk","oathf","oate","oathii","oathfi","oathfii"]), 
                                     ["oath","oathk","oathf","oathfi","oathfii","oathi","oathii","oate","eat"])
        self.assertEqual(s.findWords(board = [["o","a","b","n"],["o","t","a","e"],["a","h","k","r"],["a","f","l","v"]], words = ["oa","oaa"]), ["oa","oaa"])
        self.assertEqual(s.findWords(board = [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]], words = ["oath","pea","eat","rain"]), 
                         ["oath","eat"])
        self.assertEqual(s.findWords(board = [["a","b"],["c","d"]], words = ["abcb"]), [])


if __name__ == '__main__':
    unittest.main()